import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-buttons";
import { HomeIcon } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <nav className="z-10 relative flex justify-between items-center bg-sky-950 p-5 h-24 text-white">
            <Link
              href="/"
              className="flex items-center gap-2 text-3xl uppercase tracking-widest"
            >
              <HomeIcon />
              <span>Fire Homes</span>
            </Link>

            <ul className="flex items-center gap-6">
              <li>
                <Link
                  href="/property-search"
                  className="hover:underline uppercase tracking-widest"
                >
                  Property search
                </Link>
              </li>

              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {children}

          <Toaster closeButton richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
